# Generated by Django 3.0.8 on 2020-08-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("artworks", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="concreteartwork",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        )
    ]
